services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${LETS_ENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN_NAME}`)"

  broker:
    restart: always

  database:
    restart: always

  transcriber:
    restart: always

  sessionapi:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sessionapi.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/sessionapi`)"
      - "traefik.http.routers.sessionapi.middlewares=sessionapi-strip"
      - "traefik.http.middlewares.sessionapi-strip.stripprefix.prefixes=/sessionapi"
      - "traefik.http.middlewares.sessionapi-strip.stripprefix.forceslash=false"
      - "traefik.http.routers.sessionapi.entrypoints=websecure"
      - "traefik.http.routers.sessionapi.tls.certresolver=letsencrypt"

  scheduler:
    restart: always
