services:
  transcriber:
    healthcheck:
      disable: true
    volumes:
      - ./Transcriber:/usr/src/app/transcriber
      - /usr/src/app/transcriber/node_modules
    command: ["npm run start-live"]

  sessionapi:
    healthcheck:
      disable: true
    volumes:
      - ./Session-API:/usr/src/app/sessionapi
      - /usr/src/app/sessionapi/node_modules
    command: ["npm run start-live"]

  scheduler:
    healthcheck:
      disable: true
    volumes:
      - ./Scheduler:/usr/src/app/scheduler
      - /usr/src/app/scheduler/node_modules
    command: ["npm run start-live"]
