@echo off
echo Starting service for testing...
start /b "BotService" dotnet run --project BotService
timeout 5
echo Testing health endpoint...
curl -s http://localhost:5113/health
echo.
echo Testing Graph API connection...
curl -s http://localhost:5113/api/bot/test-connection
echo.
echo Stopping service...
taskkill /f /im BotService.exe >nul 2>&1
echo Service test completed.